version: '3.7'

services:
  reverseproxy:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t2g2/reverseproxy:stable
    depends_on:
      - webprod
      - webstaging
    ports:
      - 443:443
  webprod:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t2g2/web:stable
    depends_on:
      - apiprod
  dbprod:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t2g2/db:stable
  apiprod:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t2g2/api:stable
    environment:
      - DB_HOST=dbprod
    depends_on:
      - dbprod
  webstaging:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t2g2/web:latest
    depends_on:
      - apistaging
  dbstaging:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t2g2/db:latest
  apistaging:
    image: registry.gitlab.com/feup-tbs/ldso18-19/t2g2/api:latest
    environment:
      - DB_HOST=dbstaging
    depends_on:
      - dbstaging