# base image
FROM node:9.6.1

# set working directory
RUN mkdir /usr/gnet
WORKDIR /usr/gnet
COPY build /usr/gnet

# COPY docker/site.key /run/secrets/site.key
# COPY docker/site.crt /run/secrets/site.crt

RUN npm install -g serve
CMD serve -s build
EXPOSE 5001

# FROM nginx:alpine

# COPY build /usr/share/nginx/html
# RUN mkdir -p /run/secrets
# COPY docker/site.key /run/secrets/site.key
# COPY docker/site.crt /run/secrets/site.crt

# COPY docker/nginx.conf /etc/nginx/nginx.conf

# EXPOSE 3000

# RUN npm install -g serve
# CMD serve -s build
# CMD ["nginx", "-g", "daemon off;"]
