# base image
FROM node:9.6.1

# set working directory
RUN mkdir /usr/gnet
WORKDIR /usr/gnet
COPY build /usr/gnet

# add `/usr/src/app/node_modules/.bin` to $PATH
# ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
# COPY package.json /usr/src/app/package.json
# RUN npm install

RUN npm install -g serve
CMD serve -s build


# FROM nginx:alpine

# COPY build /usr/share/nginx/html
# RUN mkdir -p /run/secrets
# COPY docker/site.key /run/secrets/site.key
# COPY docker/site.crt /run/secrets/site.crt

# COPY docker/nginx.conf /etc/nginx/nginx.conf

# EXPOSE 3000

# RUN npm install -g serve
# CMD serve -s build
# CMD ["nginx", "-g", "daemon off;"]
